addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.8
            - g++-6
            - gcc-6

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi

script:
  - mkdir build && cd build
  - echo $CXX
