addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.8
            - g++-6
            - gcc-6
            
language: generic
matrix:
    include:
        - env: CXX=g++-6 CC=gcc-6
        - env: CXX=clang-3.8

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./hello
