--- 
dist: trusty
language: generic
matrix: 
  include: 
    - 
      addons: 
        apt: 
          packages: 
            - g++-6
            - gcc-6
          sources: 
            - ubuntu-toolchain-r-test
      env: "CXX=g++-6 CC=gcc-6"
    - 
      addons: 
        apt: 
          packages: 
            - clang-4.0
          sources: 
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
      env: "CXX=clang++-4.0 CC=clang-4.0 CXX_FLAGS=-stdlib=libc++ -lc++abi"
script: 
  - "mkdir build && cd build"
  - "cmake .."
  - make VERBOSE=1
  - ./hello
