addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-4.0
            - g++-7
            - gcc-7

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-4.0" CC="clang-4.0"; fi

script:
  - mkdir build && cd build
  - echo $CXX
