language: cpp
matrix:
  include:
  - compiler: gcc
    addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - g++-6
                - gcc-6
    env: COMPILER=g++-6
    
  - compiler: clang
    addons:
        apt:
            sources:
                - ubuntu-toolchain-r-test
                - llvm-toolchain-precise-3.8
            packages:
                - clang-3.8
    env: COMPILER=clang++-3.8

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - ./hello
