--- 
language: generic
matrix: 
  include: 
    - 
      addons: 
        apt: 
          packages: 
            - g++-6
            - gcc-6
          sources: 
            - ubuntu-toolchain-r-test
      env: "CXX=g++-6 CC=gcc-6"
    - 
      addons: 
        apt: 
          packages: 
            - clang-3.8
          sources: 
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
      env: "CXX=clang++-3.8 CC=clang-3.8"
script: 
  - "mkdir build && cd build"
  - "cmake .."
  - make
  - ./hello
